apiVersion: v1
kind: ConfigMap
metadata:
    name: biorobot-config
    namespace: default
data:
  SWARM_ENVIRONMENT: "frankfurt-simulation"
  TELEMETRY_INTERVAL_SECONDS: "5"
  TARGET_REGION: "us-east-1"